### ISSUE TITLE
cannot flatten arrays of numbers

### ISSUE THREAD

**Issue by noblige** [amirziai/flatten#16]
`print flatten_json.unflatten(flatten_json.flatten({'data' : [2]}))` :
`{'data': {'0': 2}}`

**Comment by noblige** [comment]
actually, does not have to be numbers:
`print(flatten_json.unflatten(flatten_json.flatten({'data' : ['a']})))`:
`{'data': {'0': 'a'}}`

**Comment by aquilax** [comment]
@noblige, `unflatten_list`, handles data with flattened lists

**Comment by EmSyndio** [comment]
doesn't seem to work with nested objects:

```
from flatten_json import flatten, unflatten, unflatten_list
a = {"level1":{"level2":[1,2]}}
b = flatten(a,".")
b
{'level1.level2.0': 1, 'level1.level2.1': 2}
c = unflatten(b, ".")
c
{'level1': {'level2': {'1': 2, '0': 1}}}
d = unflatten_list(b,".")
d
{'level1.level2.0': 1, 'level1.level2.1': 2}
```

**Comment by EmSyndio** [comment]
seems like the bug is not present in master, but the bug fix is not released.

**Comment by amirziai** [comment]
Just released `v0.1.6`. Try `pip install flatten_json --upgrade` and let me know if the issue is fixed.

**Comment by EmSyndio** [comment]
Works as expected. thanks a lot for the quick release.

**Comment by amirziai** [comment]
Awesome! Closing the issue.
