### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by teleyinex** [amirziai/flatten#19]
This is not a bug or anything, it's just to say thank you. Your library is really GREAT. We're now using it in our open source [PYBOSSA software](http://pybossa.com) for improving our CSV exporters with Pandas.

Again, thanks for sharing this work!

**Comment by amirziai** [comment]
@teleyinex you're very welcome. Makes me very happy that you guys are finding it useful.

**Comment by teleyinex** [comment]
So far, it works really well. It looks like we've found an issue with utf8 in the keys :-) We'll debug it, and if it's a bug I'll send you a PR.

**Comment by amirziai** [comment]
👍

**Comment by teleyinex** [comment]
Yep, it does not work when there's utf8 key/values :-) You have a new PR with tests included. It's a very simple fix.
