### ISSUE TITLE
no output, tests pass

### ISSUE THREAD

**Issue by lynxlynxlynx** [amirziai/flatten#33]
Trying this for the first time, installed via pip for python3. Does not seem to work, without giving any errors.

Running example from the docs:
```
0 $ echo '{"a": {"b": 1}}' | python3 -m flatten_json
0 $ 
```
The 0 is the exit status.

Running the test suite also passes:
```
0 $ python3 /home/zuzuzu/.local/lib/python3.6/site-packages/test_flatten.py 
............
----------------------------------------------------------------------
Ran 12 tests in 0.001s

OK
0 $
```

Any ideas?

**Comment by manycoding** [comment]
Works for me with `flatten-json 0.1.7`
```
bash-3.2$ echo '{"a": {"b": 1}}' | python3 -m flatten_json
{"a_b": 1}
```
Please double check again, updating the package. If still nothing, it could be a bash problem.

**Comment by lynxlynxlynx** [comment]
Yes, has been fixed since.
