### ISSUE TITLE
Maybe unflatten as option?

### ISSUE THREAD

**Issue by nmaas87** [amirziai/flatten#4]
First things first: Great module :)!
But I got a question, could you maybe make an also recursively working unflatten function, so that we could get the old datastructure back? (Yes, one needs to use an seperator which is not used in the keynames, that should be checked as an error while doing that, but other than that it should work :))

Thanks a lot!

**Comment by amirziai** [comment]
@nmaas87 added the functionality and it's now merged into master. Feel free to open a new issue if I've missed something.

**Comment by nmaas87** [comment]
Thank you very much :)! Looks very good!
