### ISSUE TITLE
ModuleNotFoundError for v0.1.8

### ISSUE THREAD

**Issue by alexjuda** [amirziai/flatten#65]
I'm getting import errors after upgrading to v0.1.8:

```
$ pip3 install flatten_json==0.1.8 && python3 -c "import flatten_json; print('ok')"
Collecting flatten_json==0.1.8
  Using cached https://files.pythonhosted.org/packages/a0/d3/a5d5d3ed553e059e2b844177087beb5d32cd2d19959a466b1e9b3c795995/flatten_json-0.1.8-py3-none-any.whl
Requirement already satisfied: six in ./venv/dev/lib/python3.8/site-packages (from flatten_json==0.1.8) (1.14.0)
Installing collected packages: flatten-json
  Found existing installation: flatten-json 0.1.7
    Uninstalling flatten-json-0.1.7:
      Successfully uninstalled flatten-json-0.1.7
Successfully installed flatten-json-0.1.8
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flatten_json'
```

Note that the previous one (v0.1.7) works fine:

```
$ pip3 install flatten_json==0.1.7 && python3 -c "import flatten_json; print('ok')"
Collecting flatten_json==0.1.7
  Using cached https://files.pythonhosted.org/packages/eb/a9/1e35abfc4726065f9692decb3c57cf379e5d5329befc6fa5a1ab835fffb8/flatten_json-0.1.7-py3-none-any.whl
Installing collected packages: flatten-json
  Found existing installation: flatten-json 0.1.8
    Uninstalling flatten-json-0.1.8:
      Successfully uninstalled flatten-json-0.1.8
Successfully installed flatten-json-0.1.7
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ok
```

I can see the package metadata in my virtual env, but no package source or wheel.

![image](https://user-images.githubusercontent.com/6004040/88517825-bdff9b00-cfef-11ea-9c3b-d1edd2dd97c5.png)

Perhaps something went wrong during the last release process?

Python: 3.8.1
OS: macOS 10.15.4
venv: `python3 -m venv venv`

**Comment by ecklm** [comment]
Even more suspiciously, nothing seems to have happened in the repo since February 2. No commits at all, so why the release?

**Comment by Laksh1997** [comment]
I'm getting this error as well

**Comment by amirziai** [comment]
release to pypi is a manual step for the project and there were some commits that i had not released. so i manually released yesterday.

i can confirm the issue. pypi shows that the files were [uploaded](https://pypi.org/project/flatten-json/0.1.8/#files) but for some they're not being brought in with `pip install`. i'll look into this and update this thread.

pls let me know if you know what's going on and have ideas for resolving it.

**Comment by amirziai** [comment]
also yanking `0.1.8` until this is resolved so `pip install flatten-json` should give you `0.1.7`.

**Comment by JacobSMoller** [comment]
@amirziai  seems like  `pip install flatten-json` still gives you 0.1.8

**Comment by ecklm** [comment]
> @amirziai seems like `pip install flatten-json` still gives you 0.1.8

Really?

```
$ pip search flatten-json | grep flatten-json
flatten-json (0.1.7)                                - Flatten JSON objects
```

**Comment by amirziai** [comment]
@JacobSMoller should be yanked:
https://pypi.org/project/flatten-json/0.1.8/

my understanding of a yanked release is that you can still install it by pinning but without specifying that specific version you should get the latest non-yanked version.

i see the same output that @ecklm is reporting.

**Comment by marclafountain** [comment]
I see the same pip/poetry search output that @ecklm and @amir-ziai-zefr are reporting. However, I am also still getting the 0.1.8 version when I run:

`poetry add flatten_json`

and also get the ModuleNotFoundError error under 0.1.8.

Removing 0.1.8 with

`poetry remove flatten_json`

and installing again using

`poetry add "flatten_json==0.1.7"`

has resolved the issue for me.

**Comment by freemansgit** [comment]
When will we get working 0.1.8 using pip install flatten_json==0.1.8 ?   I still experiencies problem with assert unflatten(flatten(d)) == d operation))

**Comment by amirziai** [comment]
release a new version. pls upgrade and lmk if you have issues.

**Comment by alexjuda** [comment]
Thanks @amirziai, works like a charm now!
 
Again, running
```
pip3 install flatten_json && python3 -c "import flatten_json; print('ok')"
```
works as expected, installs v0.1.13 and prints "ok".
