### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by aodj** [amirziai/flatten#67]
Does anyone know if this project is still being maintained? I've run into issue #62 and read that it was fixed in the v0.1.8 release which was released and then yanked from pypi due to a build issue.

If the project is still being maintained, is it likely to be deployed at all?
If the project is unmaintained, is there any interest in forking and fixing outstanding issues?

**Comment by amirziai** [comment]
i'm not actively maintaining the project but just released `0.1.13` that seems to have fixed #65 but lmk if you have any issues.
